# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-09 17:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.TextField()),
                ('province', models.TextField()),
                ('district', models.TextField()),
                ('community', models.TextField()),
                ('address', models.TextField()),
                ('family_name', models.TextField()),
                ('intervention_sector', models.TextField()),
                ('reluctant_houses', models.BooleanField()),
                ('members', models.IntegerField()),
                ('registration_date', models.DateField()),
                ('sex', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
