# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-09 20:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='address',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='file',
            name='community',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='file',
            name='district',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='file',
            name='family_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='file',
            name='intervention_sector',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='file',
            name='province',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='file',
            name='region',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='file',
            name='sex',
            field=models.CharField(max_length=2),
        ),
    ]
