# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-10 14:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_auto_20180109_2025'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatementTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=200)),
                ('order', models.IntegerField()),
                ('answer_value', models.BooleanField()),
            ],
        ),
    ]
