# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-10 14:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_statementtest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statementtest',
            name='answer_value',
            field=models.CharField(max_length=2),
        ),
    ]
