# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-12 16:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0008_auto_20180110_1522'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='reluctant_houses',
        ),
    ]
