# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-12 16:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0009_remove_file_reluctant_houses'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='reluctant_houses',
            field=models.NullBooleanField(default=None),
        ),
    ]
